### ISSUE TITLE
apache_request_headers() is undefined in (Nginx) FastCGI environment

### ISSUE THREAD

**Issue by vmattila** [Codaone/woocommerce_logitrail_module#7]
Referring to https://github.com/Codaone/woocommerce_logitrail_module/blob/master/logitrail-woocommerce.php#L841 , `apache_request_headers()` function is not defined in certain FastCGI environments and the plugin throws an error. 

There are couple of possible workarounds:

1) Using `$_SERVER['HTTP_AUTHORIZATION']`, anyway in Apache environment this is not available
2) Implementation of https://github.com/ralouphie/getallheaders polyfill

**Comment by mikakoi** [comment]
Solved as of https://github.com/Codaone/woocommerce_logitrail_module/releases/tag/1.0.5
