### ISSUE TITLE
Add support for total_sum parameter in Checkout HTTP Form API

### ISSUE THREAD

**Issue by vmattila** [Codaone/woocommerce_logitrail_module#8]
Instead of passing individual item price in Checkout HTTP Form API, it's now possible to set ``total_sum`` parameter. This is useful especially in bundle items, where the bundle's subitems may not have the actual price at all.

See http://logitrail-integration.readthedocs.io/en/latest/checkout/http_form_api.html#new-order-fields as well as https://github.com/logitrail/integration-docs/commit/eb20d4e71f0bc95dd35a9020b2afced172a25a22 for further details.

**Comment by mikakoi** [comment]
https://github.com/Codaone/woocommerce_logitrail_module/releases/tag/1.0.10
